@echo off

    fc /b AKA.OBJ      OBJ\AKA.OBJ          >output.lst
    fc /b BINLOG.OBJ   OBJ\BINLOG.OBJ       >>output.lst
    fc /b BULLETIN.OBJ OBJ\BULLETIN.OBJ     >>output.lst
    fc /b CDROM.OBJ    OBJ\CDROM.OBJ        >>output.lst
    fc /b CHAT.OBJ     OBJ\CHAT.OBJ         >>output.lst
    fc /b CLEANUP.OBJ  OBJ\CLEANUP.OBJ      >>output.lst
    fc /b COMBINED.OBJ OBJ\COMBINED.OBJ     >>output.lst
    fc /b DECKEY.OBJ   OBJ\DECKEY.OBJ       >>output.lst
    fc /b DL.OBJ       OBJ\DL.OBJ           >>output.lst
    fc /b EVENT.OBJ    OBJ\EVENT.OBJ        >>output.lst
    fc /b EXECHECK.OBJ OBJ\EXECHECK.OBJ     >>output.lst
    fc /b FILEAREA.OBJ OBJ\FILEAREA.OBJ     >>output.lst
    fc /b FORWARD.OBJ  OBJ\FORWARD.OBJ      >>output.lst
    fc /b FUZZY.OBJ    OBJ\FUZZY.OBJ        >>output.lst
    fc /b GIF.OBJ      OBJ\GIF.OBJ          >>output.lst
REM fc /b HANDLER.OBJ  OBJ\HANDLER.OBJ      >>output.lst
    fc /b HELP.OBJ     OBJ\HELP.OBJ         >>output.lst
    fc /b HUDSON.OBJ   OBJ\HUDSON.OBJ       >>output.lst
    fc /b IMAGE.OBJ    OBJ\IMAGE.OBJ        >>output.lst
    fc /b INPDATE.OBJ  OBJ\INPDATE.OBJ      >>output.lst
    fc /b IO.OBJ       OBJ\IO.OBJ           >>output.lst
    fc /b JAM.OBJ      OBJ\JAM.OBJ          >>output.lst
    fc /b LANGUAGE.OBJ OBJ\LANGUAGE.OBJ     >>output.lst
    fc /b LASTCALL.OBJ OBJ\LASTCALL.OBJ     >>output.lst
    fc /b LISTFILE.OBJ OBJ\LISTFILE.OBJ     >>output.lst
    fc /b LOADPEX.OBJ  OBJ\LOADPEX.OBJ      >>output.lst
    fc /b LOGIN.OBJ    OBJ\LOGIN.OBJ        >>output.lst
    fc /b MAILCHK.OBJ  OBJ\MAILCHK.OBJ      >>output.lst
    fc /b MARK.OBJ     OBJ\MARK.OBJ         >>output.lst
    fc /b MCHAT.OBJ    OBJ\MCHAT.OBJ        >>output.lst
    fc /b MENU.OBJ     OBJ\MENU.OBJ         >>output.lst
    fc /b MISC.OBJ     OBJ\MISC.OBJ         >>output.lst
    fc /b MODEM.OBJ    OBJ\MODEM.OBJ        >>output.lst
    fc /b MSG.OBJ      OBJ\MSG.OBJ          >>output.lst
    fc /b MSGAREA.OBJ  OBJ\MSGAREA.OBJ      >>output.lst
    fc /b MSGBASE.OBJ  OBJ\MSGBASE.OBJ      >>output.lst
    fc /b MSGDEL.OBJ   OBJ\MSGDEL.OBJ       >>output.lst
    fc /b MSGED.OBJ    OBJ\MSGED.OBJ        >>output.lst
    fc /b MSGEXPRT.OBJ OBJ\MSGEXPRT.OBJ     >>output.lst
    fc /b MSGFIND.OBJ  OBJ\MSGFIND.OBJ      >>output.lst
    fc /b MSGMOVE.OBJ  OBJ\MSGMOVE.OBJ      >>output.lst
    fc /b MUSIC.OBJ    OBJ\MUSIC.OBJ        >>output.lst
    fc /b NODELIST.OBJ OBJ\NODELIST.OBJ     >>output.lst
    fc /b ONLINE.OBJ   OBJ\ONLINE.OBJ       >>output.lst
    fc /b PBUSER.OBJ   OBJ\PBUSER.OBJ       >>output.lst
    fc /b POSTMSG.OBJ  OBJ\POSTMSG.OBJ      >>output.lst
    fc /b PROBOARD.OBJ OBJ\PROBOARD.OBJ     >>output.lst
    fc /b PROTOCOL.OBJ OBJ\PROTOCOL.OBJ     >>output.lst
    fc /b QSCANMSG.OBJ OBJ\QSCANMSG.OBJ     >>output.lst
    fc /b QUESTION.OBJ OBJ\QUESTION.OBJ     >>output.lst
    fc /b RAWDIR.OBJ   OBJ\RAWDIR.OBJ       >>output.lst
    fc /b READMSG.OBJ  OBJ\READMSG.OBJ      >>output.lst
REM fc /b REGIS.OBJ    OBJ\REGIS.OBJ        >>output.lst
    fc /b REPLYMSG.OBJ OBJ\REPLYMSG.OBJ     >>output.lst
    fc /b RIP.OBJ      OBJ\RIP.OBJ          >>output.lst
    fc /b SCANMSG.OBJ  OBJ\SCANMSG.OBJ      >>output.lst
    fc /b SELLANG.OBJ  OBJ\SELLANG.OBJ      >>output.lst
    fc /b SETAREA.OBJ  OBJ\SETAREA.OBJ      >>output.lst
    fc /b SHELL.OBJ    OBJ\SHELL.OBJ        >>output.lst
    fc /b SHOWANS.OBJ  OBJ\SHOWANS.OBJ      >>output.lst
    fc /b SHOWMSG.OBJ  OBJ\SHOWMSG.OBJ      >>output.lst
    fc /b SQUISH.OBJ   OBJ\SQUISH.OBJ       >>output.lst
    fc /b STACKING.OBJ OBJ\STACKING.OBJ     >>output.lst
    fc /b STRVARS.OBJ  OBJ\STRVARS.OBJ      >>output.lst
    fc /b SYSOPKEY.OBJ OBJ\SYSOPKEY.OBJ     >>output.lst
    fc /b TAG.OBJ      OBJ\TAG.OBJ          >>output.lst
    fc /b TAG_RW.OBJ   OBJ\TAG_RW.OBJ       >>output.lst
    fc /b TERMINAL.OBJ OBJ\TERMINAL.OBJ     >>output.lst
    fc /b TIMELOG.OBJ  OBJ\TIMELOG.OBJ      >>output.lst
    fc /b TIMER.OBJ    OBJ\TIMER.OBJ        >>output.lst
    fc /b TIMESTAT.OBJ OBJ\TIMESTAT.OBJ     >>output.lst
    fc /b TOPS.OBJ     OBJ\TOPS.OBJ         >>output.lst
    fc /b UL.OBJ       OBJ\UL.OBJ           >>output.lst
    fc /b USAGE.OBJ    OBJ\USAGE.OBJ        >>output.lst
    fc /b USERED.OBJ   OBJ\USERED.OBJ       >>output.lst
    fc /b USERSET.OBJ  OBJ\USERSET.OBJ      >>output.lst
    fc /b USERWIN.OBJ  OBJ\USERWIN.OBJ      >>output.lst
    fc /b VERSION.OBJ  OBJ\VERSION.OBJ      >>output.lst
    fc /b VIEWFILE.OBJ OBJ\VIEWFILE.OBJ     >>output.lst
    fc /b WORDWRAP.OBJ OBJ\WORDWRAP.OBJ     >>output.lst
    fc /b WRITEMSG.OBJ OBJ\WRITEMSG.OBJ     >>output.lst
    fc /b ZIP.OBJ      OBJ\ZIP.OBJ          >>output.lst
